name: Example of a workflow with repository variables and secrets

on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest

    env:
      JOB_MY_VAR: Variable a nivel de job

    steps:
      - name: Use vars context
        run: echo "El valor de la variable es ${{ vars.MY_VARIABLE }}"

      - name: Use secrets context
        run: echo "El valor del secreto es ${{ secrets.MY_SECRET }}"
