name: "My action"
description: "Test my action"

inputs:
  message:
    description: "Message to print"
    required: true
    default: "Hola Mundo"

runs:
  using: "composite"

  steps:
    - name: Print message
      run: echo "${{ inputs.message }}"
      shell: bash
