name: Example of a workflow with a service

on: [push]

jobs:
  service-job:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: example
        ports:
          - 3306:3306

    steps:
      - name: List files
        run: ls -al
