name: Example of a workflow with a variable

on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest

    env:
      JOB_MY_VAR: Variable a nivel de job

    steps:
      - name: Print environment variable
        env:
          STEP_MY_VAR: Variable a nivel de step
        run: echo "El valor es $STEP_MY_VAR"
