name: Example of a workflow with repository variable

on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest

    env:
      JOB_MY_VAR: Variable a nivel de job

    steps:
      - name: Use vars context
        run: echo "El valor es ${{ vars.MY_VARIABLE }}"

      - name: Use env context
        run: echo "El valor es ${{ env.JOB_MY_VAR }}"
